### ISSUE TITLE
Remove log in fields after logging in

### ISSUE THREAD

**Issue by amcdon** [CarnivorousBeehive/mystuffs.space#17]
When a user has successfully logged in, show them the success message but also remove the log in fields to prevent confusion.
![login_fields](https://cloud.githubusercontent.com/assets/1672328/7266801/6552ed2a-e875-11e4-84d0-2e1cd807dfa3.png)

**Comment by eduncan26** [comment]
@amcdon Any objections to showing a success message after redirecting them to the home page, and then creating logic that if a user is logged in they cannot get to the login page?

**Comment by amcdon** [comment]
I think that makes the most sense. I'm not real familiar with authentication so I'm not sure if there are better ways to do it.
